import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeBackground,snapshotUrl,normalizeGoal,normalizeMenu,normalizeMembers,normalizeProfile,publicIdentity,createPublicInfo} from './public-info.js';
import {chatMessage} from './live-chat.js';
test('goal only represents an active public broadcast and preserves unknown progress',()=>{const g={isEnabled:true,goal:100,spent:25,left:75,description:'目标'};assert.equal(normalizeGoal(g,false),null);assert.equal(normalizeGoal(g,true).percent,25);assert.equal(normalizeGoal({...g,spent:undefined},true).spent,null);assert.equal(normalizeGoal({...g,goal:0},true),null);assert.equal(normalizeGoal({...g,spent:120},true).percent,100);});
test('menu messages use explicit platform source, not matching amount',()=>{const m={id:1,type:'tip',modelId:3,details:{amount:5,source:'tipMenu',body:'点歌'},userData:{username:'guest'}};assert.match(chatMessage(m).text,/小费菜单.*点歌/);assert.equal(chatMessage({...m,details:{amount:5}}).tipMenu,false);const anon=chatMessage({...m,details:{...m.details,isAnonymous:true},userData:{username:'secret',id:42,userRanking:{level:10}}});assert.equal(anon.username,'匿名');assert.equal(anon.level,null);assert.ok(!JSON.stringify(anon).includes('secret'));});
test('public profile is whitelisted, hidden age and restricted photos excluded',()=>{const r=normalizeProfile({isAgeHidden:true,modelToken:'secret'}, {item:{age:24,description:'<script>hello</script>',birthDate:'private'}}, {isEnabled:true,settings:[{activity:'音乐',price:5},{activity:'bad',price:-1}]},{total:1,items:[{id:1,userId:42,userUsername:null,description:'好',score:5}]},{totalItems:2,albums:[{id:1,name:'Public',accessMode:'free',cost:0,photos:[{id:1,status:'approved',urlThumb:'https://static-proxy.strpst.com/photos/a'},{id:2,status:'approved',isHidden:true,urlThumb:'https://static-proxy.strpst.com/photos/b'}]},{id:2,accessMode:'paidOrFanClub',cost:5,photos:[]}]});assert.equal(r.age,null);assert.equal(r.menu.items.length,1);assert.equal(r.albums.items.length,1);assert.equal(r.albums.items[0].photos.length,1);assert.equal(r.reviews.items[0].author,'匿名用户');assert.ok(!JSON.stringify(r).includes('secret'));assert.ok(!JSON.stringify(r).includes('birthDate'));});
test('members are deduplicated, anonymous/invisible identities excluded',()=>{const r=normalizeMembers({members:[{user:{id:1,username:'a',userRanking:{level:20}}},{user:{id:1,username:'a'}},{user:{id:2,username:'hidden',isInvisible:true}}],guests:12});assert.equal(r.members.length,1);assert.equal(r.guests,12);assert.throws(()=>normalizeMembers({}));});
test('rejects mismatched or inaccessible model identities',()=>{const model={name:'name',source_id:'1'};assert.throws(()=>publicIdentity({user:{user:{id:2,username:'name'}}},model));assert.throws(()=>publicIdentity({user:{user:{id:1,username:'name'},isGeoBanned:true}},model));});
test('HTTP cache coalesces reads, refreshes, and reports optional endpoint failures',async()=>{let calls=0,at=0;const requests=[];const info=createPublicInfo({now:()=>at,fetcher:async(url,options)=>{calls++;requests.push(options);if(url.includes('/cam'))return Response.json({user:{user:{id:1,username:'name',status:'public'}},cam:{isCamAvailable:true,goal:{isEnabled:true,goal:100,spent:10}}});if(url.endsWith('/members'))return Response.json({members:[],guests:3});return new Response('',{status:403});}});const m={name:'name',source_id:1};await Promise.all([info.room(m),info.room(m)]);assert.equal(calls,2);at=11000;await info.room(m);assert.equal(calls,4);const p=await info.profile(m);assert.deepEqual(p.unavailable,['profile','menu','reviews','albums','background']);assert.equal(p.reviews,null);assert.ok(requests.every(r=>!r.headers.Cookie&&!r.headers.Authorization));});

test('only public approved image backgrounds and public live snapshots are exposed',()=>{assert.equal(normalizeBackground({type:'image',isUnderPreModeration:true,image:{url:'https://static-proxy.strpst.com/intro/a'}}),null);assert.equal(normalizeBackground({type:'video',video:{url:'https://static-proxy.strpst.com/a'}}),null);assert.equal(normalizeBackground({type:'image',image:{url:'https://static-proxy.strpst.com/intro/a'},settings:{heightShift:64}}).position,64);assert.equal(snapshotUrl({id:1,status:'public',snapshotTimestamp:100},{isCamAvailable:true}),'https://img.doppiocdn.net/thumbs/100/1');assert.equal(snapshotUrl({id:1,status:'private',snapshotTimestamp:100},{isCamAvailable:true}),null);});
