import React,{useEffect,useRef,useState} from 'react';
import {insightApi,useInsight,when,fileUrl,hours} from './insight-api.js';
export function ContentEditor({item,onClose,onSaved,seek=0}){
 const live=useInsight(`/content/${item.kind}/${item.id}`,5000);
 const media={...item,...live.data};
 const video=useRef(),stopAt=useRef(null),[draft,setDraft]=useState(()=>({...item})),[tags,setTags]=useState(item.tags.join('、')),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[busy,setBusy]=useState(false),[markLabel,setMarkLabel]=useState(''),[start,setStart]=useState(0),[end,setEnd]=useState('');
 const playable=['已完成','已中断'].includes(media.status)&&Number(media.bytes)>0;
 useEffect(()=>{stopAt.current=null;if(video.current?.readyState)video.current.currentTime=seek;},[seek]);
 const set=(key,value)=>{setDraft(d=>({...d,[key]:value}));setFeedback('');};
 async function save(){setBusy(true);setError('');try{const data=await insightApi(`/content/${item.kind}/${item.id}`,{title:draft.title,note:draft.note,favorite:draft.favorite,watched:draft.watched,tags:tags.split(/[、,，]/).map(t=>t.trim()).filter(Boolean),marks:draft.marks},'PUT');setDraft(d=>({...d,...data}));setFeedback('已保存');onSaved?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function addMark(){const a=Number(start),b=end===''?null:Number(end);if(!Number.isFinite(a)||a<0||a>=media.duration_seconds||b!=null&&(!Number.isFinite(b)||b<=a||b>media.duration_seconds)){setError('请输入视频内的起止秒数，结束时间须晚于开始');return;}set('marks',[...draft.marks,{start:a,end:b,label:markLabel||'时间标记'}]);setMarkLabel('');setEnd('');setError('');}
 return <section className="md-section content-editor"><div className="md-section-title"><h2>{item.name||'媒体'} · {item.kind==='highlight'?'高光':'录像'}</h2><button onClick={onClose}>关闭内容</button></div><p>{when(media.started_at||media.created_at)} · {media.status} · {hours(media.duration_seconds)}</p>
 {playable?<video ref={video} controls playsInline preload="metadata" src={fileUrl(item)} onLoadedMetadata={()=>{video.current.currentTime=Math.min(seek,Math.max(0,video.current.duration-.1));}} onTimeUpdate={()=>{if(stopAt.current!=null&&video.current.currentTime>=stopAt.current){video.current.pause();stopAt.current=null;}}} onError={()=>setError('媒体暂不可播放，请检查归档文件。')}/>:<p className="empty">{media.status} · 归档完成后可播放和标记</p>}
 <div className="insight-form"><label>标题<input aria-label="内容标题" maxLength={120} value={draft.title} onChange={e=>set('title',e.target.value)} placeholder={item.filename}/></label><label>标签<input aria-label="内容标签" value={tags} onChange={e=>setTags(e.target.value)} placeholder="用逗号或顿号分隔"/></label><label className="full">备注<textarea aria-label="内容备注" maxLength={2000} value={draft.note} onChange={e=>set('note',e.target.value)}/></label></div>
 <div className="insight-filters"><label><input type="checkbox" checked={draft.favorite} onChange={e=>set('favorite',e.target.checked)}/>收藏</label><label><input type="checkbox" checked={draft.watched} onChange={e=>set('watched',e.target.checked)}/>已看过</label>{playable&&<a href={fileUrl(item)+'?download=1'}>下载原视频</a>}</div>
 <h3>时间标记与片段</h3><p className="muted">记录起止时间即可回看片段；不会修改原视频。编辑后点击保存。</p>
 {playable&&<><div className="insight-actions"><button onClick={()=>{setStart(Number((video.current?.currentTime||0).toFixed(1)));setEnd('');}}>标记当前时间</button><button onClick={()=>setEnd(Number((video.current?.currentTime||0).toFixed(1)))}>取当前时间为结束</button></div><div className="insight-form"><label>标记说明<input aria-label="标记说明" maxLength={120} value={markLabel} onChange={e=>setMarkLabel(e.target.value)}/></label><label>起点（秒）<input aria-label="标记起点" type="number" min="0" step="0.1" value={start} onChange={e=>setStart(e.target.value)}/></label><label>终点（秒，可留空）<input aria-label="标记终点" type="number" min="0" step="0.1" value={end} onChange={e=>setEnd(e.target.value)}/></label><button onClick={addMark}>添加标记</button></div></>}
 <div className="insight-marks">{draft.marks.map((m,i)=><div key={i}><button disabled={!playable} onClick={()=>{video.current.currentTime=m.start;stopAt.current=m.end;video.current.play().catch(()=>{});}}>{m.label} · {m.start}s{m.end!=null?` — ${m.end}s`:''}</button><button aria-label={'移除标记 '+m.label} onClick={()=>set('marks',draft.marks.filter((_,n)=>i!==n))}>移除</button></div>)}</div>
 {error&&<p role="alert">{error}</p>}{feedback&&<p role="status">{feedback}</p>}<button className="primary" disabled={busy} onClick={save}>{busy?'保存中…':'保存内容信息'}</button></section>;
}
export default function ContentLibrary({model,initialKind,initialId}){
 const [q,setQ]=useState(''),[kind,setKind]=useState(''),[favorite,setFavorite]=useState(false),[unwatched,setUnwatched]=useState(false),[date,setDate]=useState(''),[session,setSession]=useState(''),[offset,setOffset]=useState(0),[selected,setSelected]=useState(null),[error,setError]=useState('');
 const feed=useInsight(`/content?model=${model?.id||''}&q=${encodeURIComponent(q)}&kind=${kind}&favorite=${favorite}&unwatched=${unwatched}&date=${date}&session=${session}&offset=${offset}`,10000);
 useEffect(()=>{setOffset(0);},[q,kind,favorite,unwatched,date,session,model?.id]);
 useEffect(()=>{let stopped=false;if(initialKind&&initialId)insightApi(`/content/${initialKind}/${initialId}`).then(j=>{if(!stopped)setSelected(j);}).catch(e=>{if(!stopped)setError(e.message);});return()=>{stopped=true;};},[initialKind,initialId]);
 return <div className="insight-library">{selected&&<ContentEditor key={selected.kind+selected.id} item={selected} onClose={()=>setSelected(null)} onSaved={feed.reload}/>}
 <section className="md-section"><div className="md-section-title"><h2>{model?'主播内容库':'个人内容库'}</h2><span>录像与高光统一整理</span></div><div className="insight-filters"><input aria-label="搜索内容" placeholder="主播、标题、标签、备注、触发原因" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="内容类型" value={kind} onChange={e=>setKind(e.target.value)}><option value="">全部内容</option><option value="recording">录像</option><option value="highlight">高光</option></select><input aria-label="内容日期" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input aria-label="内容场次 ID" type="number" min="1" placeholder="场次 ID" value={session} onChange={e=>setSession(e.target.value)}/><label><input type="checkbox" checked={favorite} onChange={e=>setFavorite(e.target.checked)}/>只看收藏</label><label><input type="checkbox" checked={unwatched} onChange={e=>setUnwatched(e.target.checked)}/>未看过</label></div>
 {(error||feed.error)&&<p role="alert">{error||feed.error}</p>}<div className="insight-feed">{feed.data?.items.map(m=><article key={m.kind+m.id}><div><time>{when(m.started_at||m.created_at)}</time><h3>{m.title||m.name||m.filename} {m.favorite?'♥':''}</h3><p>{m.kind==='highlight'?'高光':'录像'} · {m.status} · {hours(m.duration_seconds)} · {m.watched?'已看':'未看'}</p><small>{m.tags.join(' · ')||m.reasons.map(r=>r.text).join(' · ')}</small></div><button onClick={()=>{setSelected(m);setError('');}}>查看与整理</button></article>)}</div>{feed.data&&!feed.data.items.length&&<p className="empty">没有符合条件的内容</p>}<div className="insight-actions">{offset>0&&<button onClick={()=>setOffset(Math.max(0,offset-24))}>上一页</button>}{feed.data?.nextOffset!=null&&<button onClick={()=>setOffset(feed.data.nextOffset)}>下一页</button>}</div></section></div>;
}
