import React,{useEffect,useState} from 'react';
import ModelActivity from './ModelActivity.jsx';
const hours=s=>`${(Number(s)/3600).toFixed(1)}h`;
const num=v=>v==null?'—':Math.round(v).toLocaleString('zh-CN');
function DailyPlot({daily,field,label,format,bars=false}){
 const [selected,setSelected]=useState(null);const width=640,height=150,max=Math.max(1,...daily.map(d=>Number(d[field])||0));
 const x=i=>daily.length===1?width/2:i/(daily.length-1)*width;
 let path='',previous=false;daily.forEach((d,i)=>{if(d[field]==null){previous=false;return;}path+=`${previous?'L':'M'}${x(i)},${height-Number(d[field])/max*(height-12)} `;previous=true;});
 const active=daily[selected]||daily.at(-1);
 return <section className="md-section recent-plot"><h3>{label}</h3>{daily.some(d=>d[field]!=null)?<><svg viewBox={`-8 -8 ${width+16} ${height+24}`} role="img" aria-label={label} preserveAspectRatio="none">{[0,.5,1].map(v=><line key={v} x1={0} x2={width} y1={height*v} y2={height*v} stroke="#ffffff10"/>)}{!bars&&<path d={path} fill="none" stroke="#fa4263" strokeWidth="2.5"/>}{daily.map((d,i)=>d[field]==null?null:bars?<rect key={d.day} x={x(i)-Math.min(12,width/daily.length/3)} y={height-Number(d[field])/max*(height-12)} width={Math.min(24,width/daily.length/1.5)} height={Number(d[field])/max*(height-12)} rx="2" fill="#369a74"/>:<circle key={d.day} cx={x(i)} cy={height-Number(d[field])/max*(height-12)} r={selected===i?4:2.5} fill="#fa4263"/>)}{daily.map((d,i)=><rect key={'hit'+d.day} tabIndex={0} aria-label={`${d.day} ${d[field]==null?'无有效数据':format(d[field])}`} x={x(i)-width/daily.length/2} y={0} width={width/daily.length} height={height} fill="transparent" onMouseEnter={()=>setSelected(i)} onFocus={()=>setSelected(i)} onClick={()=>setSelected(i)}><title>{d.day} · {d[field]==null?'无有效数据':format(d[field])}</title></rect>)}</svg><div className="recent-axis"><span>{daily[0]?.day}</span><span>最高刻度 {format(max)}</span><span>{daily.at(-1)?.day}</span></div><p className="recent-plot-value">{active?.day} <strong>{active?.[field]==null?'无有效数据':format(active[field])}</strong></p></>:<div className="empty">尚无有效采样</div>}</section>;
}
export default function LiveRecentStats({model}){
 const [days,setDays]=useState(7),[data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let closed=false,timer;const abort=new AbortController();setData(null);setError('');async function load(){try{const r=await fetch(`/api/models/${model.id}/broadcasts?days=${days}`,{signal:abort.signal});const j=await r.json();if(!r.ok)throw Error(j.error||'读取近期数据失败');if(!closed){setData(j);setError('');}}catch(e){if(!closed)setError(e.message);}finally{if(!closed)timer=setTimeout(load,60000);}}load();return()=>{closed=true;abort.abort();clearTimeout(timer);};},[model.id,days]);
 const daily=data?.daily||[],seconds=daily.reduce((n,d)=>n+d.observed_seconds,0),active=daily.filter(d=>d.observed_seconds>0).length;
 const weighted=daily.filter(d=>d.weighted_viewers!=null),weight=weighted.reduce((n,d)=>n+d.observed_seconds,0),average=weight?weighted.reduce((n,d)=>n+Number(d.weighted_viewers)*d.observed_seconds,0)/weight:null;
 return <section className="live-recent-stats" aria-label="主播近期表现"><header><div><h2>近期表现</h2><span>UTC+8 · 每分钟更新</span></div><select aria-label="近期表现时间范围" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>近 {n} 天</option>)}</select></header>{error&&<p role="alert">{error}</p>}<div className="recent-summary">{[['直播覆盖',data?hours(seconds):'—'],['观察活跃天数',data?`${active} 天`:'—'],['观看峰值',num(data?.quality?.peak_viewers)],['期间平均观看',num(average)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="recent-plots"><DailyPlot daily={daily} field="weighted_viewers" label="每日平均观看人数" format={n=>num(n)+' 人'}/><DailyPlot daily={daily} field="observed_seconds" label="每日直播覆盖时长" format={hours} bars/></div><p className="recent-footnote">时长与均值按有效采样区间统计；观看曲线缺口表示无有效数据，不代表人数为零。</p><ModelActivity key={model.id} id={model.id}/></section>;
}
