import {roomLabel} from './room-state.js';
import ProxySettings from './ProxySettings.jsx';
import {useNotifications,BrowserNotificationSetting} from './BrowserNotifications.jsx';
import ModelDashboard from './ModelDashboard.jsx';
import PollingSettings from './PollingSettings.jsx';
import ModelDirectory from './ModelDirectory.jsx';
const LivePlayer=React.lazy(()=>import('./LivePlayer.jsx')); 
import WatchLiveLink from './WatchLiveLink.jsx';
import ModelCover from './ModelCover.jsx';
import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Menu,ChartNoAxesColumnIncreasing,Search,CalendarDays,Globe,Bell,ChevronDown,ChevronRight,ChevronLeft,House,Users,Monitor,Video,Settings,Heart,Eye,Flame,Clock,Plus,Trash2,X,RefreshCw,Check,ArrowLeft,HardDrive,FileText,AlertCircle,ShieldCheck,Grid2X2,List,SlidersHorizontal,Download,Radio,Activity,Save,ExternalLink} from 'lucide-react';
import './style.css';

import ModelRecording from './ModelRecording.jsx';
const nav=[['dashboard','Dashboard','数据总览',House],['discover','Discover','发现主播',Search],['models','Following','我的关注',Users],['monitor','Monitor','实时监控',Monitor],['recordings','Recordings','录像管理',Video],['alerts','Alerts','提醒通知',Bell],['settings','Settings','系统设置',Settings]];
const num=n=>n==null?'—':Number(n).toLocaleString('en-US');
const time=t=>t?new Date(t).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}):'—';
const country=c=>{try{return c==='未知'?c:new Intl.DisplayNames(['zh-CN'],{type:'region'}).of(c.toUpperCase());}catch{return c;}};
async function api(url,options){const r=await fetch('/api'+url,{...options,headers:{'Content-Type':'application/json',...options?.headers}});const j=await r.json();if(!r.ok)throw new Error(j.error||'请求失败');return j;}
function Icon({icon:Icon,size=20,...props}){return <Icon size={size} strokeWidth={1.8} {...props}/>;}
function Panel({title,icon=ChartNoAxesColumnIncreasing,action,children,className=''}){return <section className={'panel '+className}><div className="panel-head"><h3><Icon icon={icon}/>{title}</h3>{action}</div>{children}</section>;}
function Empty({icon:Glyph=Activity,title='暂无记录',text='数据将在采集后显示',children}){return <div className="empty"><Glyph size={32}/><strong>{title}</strong><span>{text}</span>{children}</div>;}
function Avatar({model,large=false}){return <div className={'avatar '+(large?'large':'')} style={{'--avatar':model?.color||'#896c78'}}>{model?.name?.slice(0,2).toUpperCase()||'SC'}</div>;}
function Status({model}){return <span className={'status '+(!model.fresh?'muted':model.online?'green':'muted')}><i/>{!model.fresh?'待更新':roomLabel(model.room_status)}</span>;}
function Toggle({on,onChange,label}){return <button className={'toggle '+(on?'on':'')} onClick={onChange} aria-label={label} role="switch" aria-checked={on}><span/></button>;}
function Stat({icon=Users,label,value,color='red',sub,delta}){return <div className="stat"><div className={'stat-icon '+color}><Icon icon={icon} size={29}/></div><div><span>{label}</span><strong>{value}</strong>{delta!=null&&<b className={delta<0?'red-text':'green'}>{delta<0?'▼':'▲'} {Math.abs(delta)}%</b>}<small>{sub}</small></div></div>;}
function Chart({data=[],detail=false}){
 const [hover,setHover]=useState(null);const w=700,h=220;const max=Math.max(10,...data.map(p=>p.value))*1.16;
 const pts=data.map((p,i)=>[data.length===1?w/2:i/(data.length-1)*w,h-p.value/max*h]);
 const line=pts.map((p,i)=>(i?'L':'M')+p.join(',')).join(' ');const selected=hover==null?data.length-1:hover;
 return <div className="chart">{!data.length?<Empty title="正在积累真实采样" text="首轮采集完成后显示趋势"/>:<><div className="chart-main"><div className="axis">{[1,.75,.5,.25,0].map(n=><span key={n}>{num(Math.round(max*n))}</span>)}</div><svg preserveAspectRatio="none" viewBox={`-5 -10 ${w+10} ${h+20}`} role="img" aria-label="真实观看人数历史曲线" onMouseLeave={()=>setHover(null)}><defs><linearGradient id={detail?'detailFill':'chartFill'} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#fa284e" stopOpacity=".32"/><stop offset="100%" stopColor="#fa284e" stopOpacity=".025"/></linearGradient></defs>{[0,.25,.5,.75,1].map(n=><line key={'h'+n} x1="0" x2={w} y1={h*n} y2={h*n} className="grid-line"/>)}{[0,.125,.25,.375,.5,.625,.75,.875,1].map(n=><line key={'v'+n} y1="0" y2={h} x1={w*n} x2={w*n} className="grid-line"/>)}{pts.length>1&&<path d={line+` L${w},${h} L0,${h} Z`} fill={`url(#${detail?'detailFill':'chartFill'})`}/>}<path d={line} fill="none" stroke="#ff3156" strokeWidth="3.2" strokeLinejoin="round"/>{pts.map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r={i===selected?5:2} fill={i===selected?'#fff':'#ff3156'} stroke="#ff3156" strokeWidth="3"/>)}{pts.map((p,i)=><rect key={'hit'+i} x={p[0]-Math.max(8,w/data.length/2)} y="0" width={Math.max(16,w/data.length)} height={h} fill="transparent" onMouseEnter={()=>setHover(i)}/> )}</svg></div><div className="chart-labels">{data.filter((_,i)=>i===0||i===data.length-1||(data.length>8&&i%Math.ceil(data.length/6)===0)).map(p=><span key={p.time}>{time(p.time)}</span>)}</div><div className="chart-caption"><i className="dot"/>{time(data[selected]?.time)}<strong>{num(Math.round(data[selected]?.value||0))} 人观看</strong><span>真实采样 · {data.length} 个时间点</span></div></>}</div>;
}
function Heatmap({data=[]}){const max=Math.max(1,...data.map(d=>d.value));return <div className="heatmap"><div className="heat-grid">{['周一','周二','周三','周四','周五','周六','周日'].map((day,d)=><React.Fragment key={day}><span>{day}</span>{Array.from({length:24},(_,h)=>{const value=data.find(p=>p.day===d+1&&p.hour===h)?.value;return <div key={h} title={`${day} ${h}:00 · ${value==null?'未采样':num(Math.round(value))+' 平均观看'}`} style={{background:value==null?'#24272a':`rgba(255,43,77,${.22+.78*value/max})`}}/>;})}</React.Fragment>)}</div><div className="heat-labels"><span>00</span><span>04</span><span>08</span><span>12</span><span>16</span><span>20</span></div><div className="heat-legend">较低 <i style={{background:'#52212a'}}/><i style={{background:'#912537'}}/><i style={{background:'#dc2c48'}}/><i style={{background:'#ff3756'}}/> 较高 <span>灰色：未采样</span></div></div>;}
function ModelCard({m,compact=false,openModel,updateModel,onRecord}){return <article className={'model-card '+(compact?'compact':'')}><button className="model-cover" onClick={()=>openModel(m)} style={{'--cover':m.color}}><ModelCover model={m}/><div className="cover-top"><Status model={m}/><span><Users size={13}/>{m.fresh&&m.online?num(m.viewers):'—'}</span><ShieldCheck size={17}/></div><div className="identity"><Avatar model={m} large/><span className="identity-hint">监察对象 · {m.source_id}</span></div><div className="cover-bottom"><strong>{m.name}</strong><span>{country(m.country)}</span></div></button><div className="model-tags"><span>{m.room_status==='public'?'公开直播':m.room_status}</span><span>{m.fresh?'采样有效':'待更新'}</span></div><div className="model-actions"><button onClick={()=>openModel(m,'live')}><Radio size={18}/>看直播</button><button className={m.favorite?'active':''} onClick={()=>updateModel(m,'favorite')}><Heart size={18} fill={m.favorite?'currentColor':'none'}/>{m.favorite?'已关注':'关注'}</button><button className={m.monitored?'active':''} onClick={()=>updateModel(m,'monitored')}><Monitor size={18}/>监控</button><button onClick={()=>openModel(m)}><Eye size={18}/>详情</button><button onClick={()=>onRecord(m)}><Video size={18}/>留档</button></div></article>;}
function App(){
 const [official,setOfficial]=useState({query:'',models:[],total:0,busy:false,error:''});

 const [storage,setStorage]=useState(null),[storagePath,setStoragePath]=useState('');
 const [state,setState]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(/^#(detail|live)\//.test(location.hash)?location.hash.slice(1).split('/')[0]:location.hash.slice(1)||'dashboard'),[selected,setSelected]=useState(/^#(detail|live)\//.test(location.hash)?Number(location.hash.split('/')[1]):null),[query,setQuery]=useState(''),[region,setRegion]=useState('全部地区'),[online,setOnline]=useState('all'),[sort,setSort]=useState('viewers'),[min,setMin]=useState(''),[max,setMax]=useState(''),[pageNo,setPageNo]=useState(1),[list,setList]=useState(false),[toast,setToast]=useState(''),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[collapsed,setCollapsed]=useState(false),[history,setHistory]=useState([]),[days,setDays]=useState(7),[note,setNote]=useState('');

 useEffect(()=>{api('/storage').then(s=>{setStorage(s);setStoragePath(s.directory);}).catch(e=>setToast(e.message));},[]);
 useEffect(()=>{if(modelForNote())setNote(modelForNote().note||'');function modelForNote(){return state?.models.find(m=>m.id===selected);}},[selected,!!state]);
 async function load(){try{setState(await api('/state'));setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{load();const t=setInterval(load,(state?.polling?.trackedSeconds||5)*1000);const hash=()=>{const h=location.hash.slice(1)||'dashboard';if(/^(detail|live)\//.test(h)){setSelected(Number(h.split('/')[1]));setPage(h.split('/')[0]);}else{setPage(h);setSelected(null);}};window.addEventListener('hashchange',hash);return()=>{clearInterval(t);window.removeEventListener('hashchange',hash);};},[state?.polling?.trackedSeconds]);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement;const dialog=document.querySelector('.modal');const items=()=>[...dialog.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(el=>!el.disabled);items()[1]?.focus();const handler=e=>{if(e.key==='Escape'){setModal(null);return;}if(e.key==='Tab'){const nodes=items();const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus();};},[modal]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{setPageNo(1);},[query,region,online,min,max,page]);
 useEffect(()=>{if(!selected)return;let cancel=false;setHistory([]);api(`/models/${selected}/history?days=${days}`).then(r=>{if(!cancel)setHistory(r);}).catch(e=>setToast(e.message));return()=>{cancel=true;};},[selected,days,state?.collector?.id]);
 async function mutate(url,method,body){try{await api(url,{method,body:body?JSON.stringify(body):undefined});await load();setToast('已保存');return true;}catch(e){setToast(e.message);return false;}}
 const go=(p,{leaveLive=false}={})=>{if(page==='live'&&!leaveLive){window.open('#'+p,'_blank','noopener,noreferrer');return;}setPage(p);location.hash=p;setSelected(null);};
 const models=state?.models||[];const model=models.find(m=>m.id===selected)||official.models.find(m=>m.id===selected);const current=models.filter(m=>m.fresh&&m.online);const monitored=models.filter(m=>m.monitored);const recordings=state?.recordings||[];const rules=state?.rules||[];const events=state?.events||[];
 const notifications=useNotifications(events,!!state,page);
 const openModel=(m,destination='detail')=>{setState(s=>({...s,models:s.models.some(x=>x.id===m.id)?s.models.map(x=>x.id===m.id?{...x,...m}:x):[...s.models,m]}));setSelected(m.id);setNote(m.note||'');setPage(destination);const previous=location.hash||'#dashboard',target='#'+destination+'/'+m.id;if(previous!==target){location.hash=target;if(destination==='live')window.history.replaceState({...window.history.state,liveReturn:previous},'');}};
 const backFromLive=()=>{const from=window.history.state?.liveReturn;if(typeof from==='string'&&/^#(dashboard|discover|models|monitor|recordings|alerts|settings|detail\/\d+|live\/\d+)$/.test(from))window.history.back();else go('models',{leaveLive:true});};
 const smallLink=(text,target)=><button className="text-button" onClick={()=>go(target)}>{text}<ChevronRight size={15}/></button>;
 const updateModel=(m,key)=>mutate('/models/'+m.id,'PATCH',{[key]:!m[key]});
 const average=current.length?Math.round(current.reduce((sum,m)=>sum+m.viewers,0)/current.length):0;
 const titles={dashboard:['欢迎回来！','实时掌握主播动态与关键趋势，集中管理监察工作。'],discover:['发现主播','搜索官网主播，找到感兴趣的直播并加入关注。'],models:['我的关注','查看已关注主播的在线状态、观看人数和直播动态。'],monitor:['监控中心','设置监控规则，跟踪关注主播动态，及时获取重要事件提醒。'],recordings:['录像管理','管理监察留档、录制任务及存储记录。'],alerts:['提醒通知','查看监控规则触发的站内事件与采集状态。'],settings:['系统设置','管理数据来源、采集状态及基础设施。']};
 function Ranking({limit=5}){return <table className="ranking"><thead><tr><th>#</th><th>主播</th><th>当前观看</th><th>采样变化</th><th>状态</th></tr></thead><tbody>{models.filter(m=>m.fresh&&m.online).slice(0,limit).map((m,i)=><tr key={m.id} onClick={()=>openModel(m)} tabIndex="0" onKeyDown={e=>e.key==='Enter'&&openModel(m)}><td className={'rank r'+i}>{i+1}</td><td><div className="name-cell"><Avatar model={m}/><span>{m.name}</span></div></td><td>{num(m.viewers)}</td><td className={m.growth==null?'muted':m.growth<0?'red-text':'green'}>{m.growth==null?'—':`${m.growth<0?'▼':'▲'} ${Math.abs(m.growth)}%`}</td><td><Status model={m}/></td></tr>)}</tbody></table>;}

 return <div className={collapsed?'app collapsed':'app'}><header className="topbar"><button className="menu" aria-label="折叠侧边栏" onClick={()=>setCollapsed(!collapsed)}><Menu size={27}/></button><a className="brand" href="#dashboard" onClick={e=>{e.preventDefault();go('dashboard');}}><ChartNoAxesColumnIncreasing size={43} strokeWidth={3}/><div><b>SC Insight</b><small>More Data, Better Insights</small></div></a>{!['models','discover','live'].includes(page)&&<label className="global-search"><Search size={20}/><input placeholder="搜索主播、用户名或房间 ..." value={query} onChange={e=>{setQuery(e.target.value);if(page!=='discover'&&page!=='models')go('discover');}}/></label>}<button className="bell" aria-label="提醒通知" onClick={()=>go('alerts')}><Bell size={26}/>{notifications.unread>0&&<b>{notifications.unread}</b>}</button></header>
 <aside className="sidebar"><nav>{nav.map(([id,en,zh,Glyph])=><button key={id} aria-label={en+' '+zh} className={(page===id||(['detail','live'].includes(page)&&id==='models')?'selected':'')} onClick={()=>go(id)}><Glyph size={23}/><span>{en}<small>{zh}</small></span></button>)}</nav><div className="side-note"><ShieldCheck size={22}/><strong>数据让洞察更简单</strong><span>Better Data<br/>A Smarter View</span><Activity size={38}/></div></aside>
 <main className={page==='live'?'live-page-main':''}>{error&&<div className="error-banner"><AlertCircle size={17}/>{error}<button onClick={load}>重试</button></div>}{!['detail','live'].includes(page)&&<div className="page-title"><div><h1>{(titles[page]||titles.dashboard)[0]}</h1><p>{(titles[page]||titles.dashboard)[1]}</p></div><div className="page-status"><span>{new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</span><small className={state?.collector?.status==='success'?'green':'muted'}><i className="dot"/>{state?.collector?.status==='success'?'真实数据 · 按配置采集':state?.collector?.status==='running'?'正在采集':state?.collector?.status==='error'?'采集异常':'等待采集'} · {time(state?.collector?.finished_at)}</small></div></div>}
 {state?.polling&&['models','monitor','dashboard'].includes(page)&&<p className="footnote">关注 / 监控每 {state.polling.trackedSeconds} 秒查询 · 上轮成功 {state.polling.tracked.count} 位，失败 {state.polling.tracked.failed} 位 · {state.polling.tracked.lastFinished?new Date(state.polling.tracked.lastFinished).toLocaleTimeString():'等待首轮采集'}{state.polling.tracked.error&&` · ${state.polling.tracked.error}`}</p>}
 {!state?<Empty title="连接监察数据服务" text="正在读取 PostgreSQL 数据…"/>:<>
 {page==='dashboard'&&<><div className="stats five"><Stat label="采样在线主播" value={num(current.length)} sub="当前有效采样"/><Stat icon={Eye} label="关注主播在线" value={num(current.filter(m=>m.favorite).length)} color="purple" sub={`共 ${models.filter(m=>m.favorite).length} 人关注`}/><Stat icon={Video} label="正在录制" value={recordings.filter(r=>r.status==='录制中').length} color="blue" sub={state.worker?.ready?'后台录制服务已就绪':'录制服务未就绪'}/><Stat icon={ChartNoAxesColumnIncreasing} label="平均观看人数" value={num(average)} color="green-bg" sub="当前在线采样均值"/><Stat icon={Users} label="24小时新增采集" value={num(models.filter(m=>Date.now()-new Date(m.created_at)<86400000).length)} color="amber" sub={`来自 ${new Set(models.map(m=>m.country)).size} 个国家 / 地区`}/></div><div className="dashboard-middle"><Panel title="24小时公开列表抽样观看趋势" action={<span className="head-metric">当前有效采样观看 <b>{num(current.reduce((s,m)=>s+m.viewers,0))}</b></span>}><Chart data={state.history}/></Panel><Panel title="观看人数排行" icon={Flame} action={smallLink('查看全部','discover')}><Ranking/></Panel></div><div className="dashboard-bottom"><Panel title="最近采样主播" icon={Clock} action={smallLink('查看全部','models')}><div className="recent-list">{models.filter(m=>m.last_seen_at).sort((a,b)=>new Date(b.last_seen_at)-new Date(a.last_seen_at)).slice(0,5).map(m=><button key={m.id} onClick={()=>openModel(m)}><Avatar model={m}/><strong>{m.name}</strong><span>{time(m.last_seen_at)}</span><Status model={m}/></button>)}</div></Panel><Panel title="录制任务队列" icon={Video} action={smallLink('查看全部','recordings')}>{recordings.filter(r=>['排队中','连接中','录制中','归档中'].includes(r.status)).length?<div className="timeline">{recordings.filter(r=>['排队中','连接中','录制中','归档中'].includes(r.status)).map(r=><div key={r.id}><strong>{r.name||'浏览器媒体'}</strong><span>{r.status} · {r.duration}</span></div>)}</div>:<Empty icon={Video} title="暂无进行中的录制" text="真实录制任务将在这里显示"/>}</Panel><Panel title="每周抽样平均观看热度"><Heatmap data={state.heatmap}/></Panel></div><div className="scope-note"><Radio size={13}/>{state.scope} · 不含未采集房间，历史数据从首次采集开始累计</div></>}
 {(page==='discover'||page==='models')&&<ModelDirectory key={page} mode={page} models={models} Card={ModelCard} cardProps={{openModel,updateModel,onRecord:m=>setModal({type:'record',model:m})}} initialQuery={page==='discover'?query:''} onResults={r=>{setOfficial(r);void load();}} onDiscover={()=>go('discover')}/>}
 {page==='live'&&(model?<React.Suspense fallback={<p role="status">正在加载直播页…</p>}><LivePlayer refreshSeconds={state?.polling?.trackedSeconds||5} model={model} onBack={backFromLive} onFollow={()=>updateModel(model,'favorite')} onRecord={()=>setModal({type:'record',model})}/></React.Suspense>:<Empty title={state?'主播不存在':'正在加载主播…'}><button onClick={()=>go('discover')}>返回主播列表</button></Empty>)}
 {page==='detail'&&model&&<ModelDashboard key={model.id} recordings={recordings} onChange={load} model={model} history={history} days={days} setDays={setDays} Chart={Chart} refreshSeconds={state?.polling?.trackedSeconds||5} onBack={()=>go('models')} onLive={()=>openModel(model,'live')} onFollow={()=>updateModel(model,'favorite')} onMonitor={()=>updateModel(model,'monitored')} onRecord={()=>setModal({type:'record',model})} onNote={note=>mutate('/models/'+model.id,'PATCH',{note})}/>}
 {page==='monitor'&&<><div className="stats four"><Stat icon={Settings} label="启用的监控规则" value={num(rules.filter(r=>r.enabled).length)} color="blue" sub="站内事件提醒"/><Stat icon={Bell} label="今日触发提醒" value={num(events.filter(e=>new Date(e.created_at).toDateString()===new Date().toDateString()).length)} color="purple" sub="最近 50 条事件内"/><Stat icon={Users} label="当前监控主播" value={num(monitored.length)} color="green-bg" sub="已加入监察名单"/><Stat icon={AlertCircle} label="采集任务状态" value={state.collector?.status==='success'?'正常':'待检查'} sub={state.collector?.error||'按系统设置自动采样'}/></div><div className="monitor-layout"><div className="right-stack"><Panel title="监控规则" icon={Settings} action={<button className="primary" onClick={()=>setModal({type:'rule'})}><Plus size={17}/>新建规则</button>}><table><thead><tr><th>启用</th><th>规则名称</th><th>触发条件</th><th>通知方式</th><th>操作</th></tr></thead><tbody>{rules.map(r=><tr key={r.id}><td><Toggle on={r.enabled} onChange={()=>mutate('/rules/'+r.id,'PATCH',{enabled:!r.enabled})} label={r.name}/></td><td>{r.name}</td><td className="muted">{r.condition}</td><td><Bell size={17}/></td><td><button className="icon-button" aria-label={'删除规则 '+r.name} onClick={()=>setModal({type:'deleteRule',rule:r})}><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!rules.length&&<Empty icon={Settings} title="创建第一条监控规则" text="支持上线通知与观看人数阈值，作用于监察名单"/>}<p className="footnote">监控名单独立采集，状态变化触发提醒；请求失败保留上次数据并显示错误。</p></Panel><Panel title="监控主播列表" icon={Users} action={smallLink('全部主播','models')}><div className="monitor-grid">{monitored.map(m=><div className="monitor-card" key={m.id}><button onClick={()=>openModel(m)}><Avatar model={m}/><div><strong>{m.name}</strong><Status model={m}/></div></button><div><b>{num(m.viewers)}</b> <small>观看</small><button className="icon-button" aria-label={'移出监察 '+m.name} onClick={()=>updateModel(m,'monitored')}><X size={15}/></button></div></div>)}</div>{!monitored.length&&<Empty icon={Users} title="尚未添加监控主播" text="在主播列表中点击“监控”加入监察名单"><button onClick={()=>go('models')}>选择主播<ChevronRight size={16}/></button></Empty>}</Panel></div><div className="right-stack"><Panel title="事件动态" icon={Clock} action={smallLink('查看全部','alerts')}>{events.length?<div className="timeline">{events.slice(0,6).map(e=><div key={e.id}><time>{time(e.created_at)}</time><i/><div><strong>{e.title}</strong><p>{e.detail}</p></div></div>)}</div>:<Empty icon={Bell} title="暂无触发事件" text="命中监控规则后，事件将在这里出现"/>}</Panel><Panel title="通知设置" icon={Bell}><div className="notification-row"><div className="notify-icon"><Bell size={22}/></div><div><strong>站内通知</strong><small>事件中心展示监控提醒</small></div><span className="status green"><i/>已启用</span></div><BrowserNotificationSetting notifications={notifications}/>{['Telegram 通知','邮件通知','Webhook'].map(n=><div className="notification-row" key={n}><div className="notify-icon muted"><Bell size={19}/></div><div><strong>{n}</strong><small>尚未配置外部通知通道</small></div><span className="muted">待接入</span></div>)}</Panel></div></div></>}
 {page==='recordings'&&<><ModelRecording models={models} onChange={load}/><div className="stats five"><Stat icon={Video} label="录像总数" value={num(recordings.length)} sub="实际留档记录"/><Stat icon={CalendarDays} label="今日新增" value={recordings.filter(r=>new Date(r.created_at).toDateString()===new Date().toDateString()).length} color="purple" sub={state.worker?.ready?'录制服务已就绪':state.worker?.error||'录制服务未就绪'}/><Stat icon={HardDrive} label="存储已使用" value={`${(recordings.reduce((sum,r)=>sum+Number(r.bytes||0),0)/1048576).toFixed(1)} MB`} color="blue" sub="已登记录像文件"/><Stat icon={FileText} label="平均大小" value={`${(recordings.reduce((sum,r)=>sum+Number(r.bytes||0),0)/Math.max(1,recordings.length)/1048576).toFixed(1)} MB`} color="green-bg" sub="按录像台账计算"/><Stat icon={AlertCircle} label="失败任务" value={recordings.filter(r=>r.status==='失败').length} sub="实际失败记录"/></div><div className="recording-layout"><div className="right-stack"><section className="panel filter-panel"><div className="record-filter"><div className="input-icon"><Search size={18}/><input aria-label="搜索录像" placeholder="搜索主播名称或录像文件…" value={query} onChange={e=>setQuery(e.target.value)}/></div><span className="muted">全部状态</span><button onClick={()=>setModal({type:'record'})}><Plus size={17}/>新建留档</button></div></section><Panel title="录像文件" icon={Video}><table><thead><tr><th>主播 / 文件</th><th>录像时间</th><th>时长</th><th>大小</th><th>状态</th></tr></thead><tbody>{recordings.filter(r=>((r.name||'浏览器媒体')+r.filename).toLowerCase().includes(query.toLowerCase())).map(r=><tr key={r.id}><td>{r.name||'浏览器媒体'}<small className="block">{r.filename}</small></td><td>{new Date(r.created_at).toLocaleString('zh-CN')}</td><td>{r.duration}</td><td>{r.size}</td><td>{r.status}{r.error&&<small className="block red-text">{r.error}</small>}{['排队中','连接中','录制中'].includes(r.status)&&<button onClick={()=>mutate('/recordings/'+r.id+'/stop','POST',{})}>停止</button>}{['已完成','已中断'].includes(r.status)&&Number(r.bytes)>0&&<a href={'/api/recordings/'+r.id+'/file?download=1'}>下载</a>}</td></tr>)}</tbody></table>{!recordings.length&&<Empty icon={Video} title="尚无监察录像" text="在上方输入主播名称开始后台录制，完成后将在此归档。"><button className="primary" onClick={()=>setModal({type:'record'})}><Plus size={16}/>配置监察留档</button></Empty>}<div className="table-footer">共 {recordings.length} 条记录<span>仅展示实际留档结果</span></div></Panel></div><div className="right-stack"><Panel title="存储使用情况" icon={HardDrive}><div className="storage-donut"><div><strong>—</strong><span>{storage?'目录已就绪':'正在连接'}</span></div></div><p className="footnote">{storage?.directory||'正在读取保存目录'}</p></Panel><Panel title="转码任务队列" icon={RefreshCw}><Empty icon={FileText} title="暂无转码任务" text="录制任务进度显示在媒体捕获面板中"/></Panel><Panel title="录像预览" icon={Video}><Empty icon={ShieldCheck} title="尚未选择录像" text="预览仅面向获授权的监察留档"/></Panel></div></div></>}
 {page==='alerts'&&<div className="right-stack"><Panel title="通知偏好" icon={Bell}><BrowserNotificationSetting notifications={notifications}/></Panel><div className="stats four"><Stat label="事件总数" icon={Bell} value={num(events.length)} sub="最近 50 条事件"/><Stat label="启用规则" icon={Settings} value={rules.filter(r=>r.enabled).length} color="blue" sub="应用于监察名单"/><Stat label="监察对象" icon={Users} value={monitored.length} color="green-bg" sub="当前名单"/><Stat label="采集状态" icon={Radio} value={state.collector?.status==='success'?'正常':'异常'} color="purple" sub={time(state.collector?.finished_at)}/></div><Panel title="事件记录" icon={Bell} action={<button onClick={notifications.markRead}>全部标为已读</button>}>{events.length?<table><thead><tr><th>时间</th><th>主播</th><th>事件</th><th>详情</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString('zh-CN')}</td><td>{e.name}</td><td>{e.title}</td><td>{e.detail}</td></tr>)}</tbody></table>:<Empty icon={Bell} title="暂无提醒" text="先添加监察对象和监控规则，事件将在触发后保存。"/>}</Panel></div>}
 {page==='settings'&&<><PollingSettings onChange={load}/><ProxySettings/></>}
 {page==='settings'&&<div className="settings-layout"><Panel title="数据采集" icon={Radio}><div className="info-rows"><div><span>数据源</span><strong>Stripchat 公开列表元数据</strong></div><div><span>采样范围</span><strong>分组列表抽样 · 非全站</strong></div><div><span>采集间隔</span><strong>60 秒</strong></div><div><span>最近采集数量</span><strong>{num(state.collector?.count)} 位主播</strong></div><div><span>最近完成时间</span><strong>{state.collector?.finished_at?new Date(state.collector.finished_at).toLocaleString('zh-CN'):'—'}</strong></div><div><span>执行状态</span><strong className={state.collector?.status==='success'?'green':'red-text'}>{state.collector?.status||'等待中'}</strong></div>{state.collector?.error&&<p className="red-text">{state.collector.error}</p>}</div><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/collect',{method:'POST'});await load();setToast('已完成真实数据采集');}catch(e){setToast(e.message);}finally{setBusy(false);}}}><RefreshCw size={17} className={busy?'spin':''}/>{busy?'采集中…':'立即采集'}</button></Panel><div className="right-stack"><Panel title="PostgreSQL 数据库" icon={HardDrive}><div className="info-rows"><div><span>连接状态</span><strong className="green">已连接</strong></div><div><span>数据库</span><strong>sc_insight</strong></div><div><span>持久化内容</span><strong>主播 / 采样 / 规则 / 事件 / 备注</strong></div></div></Panel><Panel title="录像存储设置" icon={HardDrive}><form onSubmit={async e=>{e.preventDefault();try{const s=await api('/storage',{method:'PUT',body:JSON.stringify({directory:storagePath})});setStorage(s);setToast('录像保存目录已更新');}catch(e){setToast(e.message);}}}><label className="storage-label">保存目录<input aria-label="录像保存目录" value={storagePath} onChange={e=>setStoragePath(e.target.value)} required placeholder="输入本机或 NAS 绝对路径"/></label><div className="info-rows"><div><span>磁盘可用空间</span><strong>{storage?.space?`${(storage.space.available/1073741824).toFixed(1)} GB`:'—'}</strong></div></div><button className="primary" type="submit"><Save size={16}/>保存设置</button></form><p className="footnote">默认保存在项目 storage/recordings 目录。更改目录仅影响后续录像，已有文件保留原位。</p></Panel><Panel title="访问范围" icon={ShieldCheck}><p className="footnote">当前为本机开发服务。多用户部署前需配置登录、权限和审计。</p></Panel></div></div>}
 </>}</main>
 {toast&&<div className="toast" role="status"><AlertCircle size={18}/>{toast}<button aria-label="关闭提示" onClick={()=>setToast('')}><X size={15}/></button></div>}
 {modal&&<div className="modal-overlay" onClick={()=>setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="关闭弹窗" onClick={()=>setModal(null)}><X size={21}/></button>{modal.type==='rule'?<><h2 id="modal-title">新建监控规则</h2><p>规则应用于监察名单，命中后生成站内提醒。</p><form onSubmit={async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const condition=fd.get('type')==='viewers'?`观众数 ≥ ${fd.get('threshold')}`:'主播上线时';if(await mutate('/rules','POST',{name:fd.get('name'),condition}))setModal(null);}}><label>规则名称<input autoFocus name="name" required maxLength={80} placeholder="例如：高观看人数核查"/></label><label>触发条件<select name="type"><option value="viewers">观众数达到阈值</option><option value="online">主播上线</option></select></label><label>观看人数阈值<input type="number" name="threshold" min="1" max="99999999" defaultValue="3000" required/></label><div className="modal-actions"><button type="button" onClick={()=>setModal(null)}>取消</button><button className="primary" type="submit">创建规则</button></div></form></>:modal.type==='deleteRule'?<><h2 id="modal-title">删除监控规则</h2><p>确定删除“{modal.rule.name}”？已生成的事件记录会保留。</p><div className="modal-actions"><button onClick={()=>setModal(null)}>取消</button><button className="primary" onClick={async()=>{if(await mutate('/rules/'+modal.rule.id,'DELETE'))setModal(null);}}>删除规则</button></div></>:<><h2 id="modal-title">新建录制任务</h2><ModelRecording initialTarget={modal.model?.name||''} models={models} onChange={load} onCreated={()=>{setModal(null);if(page!=='live')go('recordings');}}/></>}</section></div>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
