import React,{useEffect,useState} from 'react';
const when=value=>value?new Date(value).toLocaleString('zh-CN'):'—';
export default function ModelHighlights({model,onChange}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState(null),[before,setBefore]=useState(null),[pages,setPages]=useState([]),[draft,setDraft]=useState(null),[version,setVersion]=useState(0);
 useEffect(()=>{let stopped=false,timer;const controller=new AbortController();
  async function load(){try{const r=await fetch(`/api/models/${model.id}/highlights${before?'?before='+before:''}`,{signal:controller.signal});const j=await r.json();if(!r.ok)throw new Error(j.error||'高光读取失败');if(!stopped){setData(j);setError('');}}catch(e){if(!stopped)setError(e.message);}finally{if(!stopped)timer=setTimeout(load,5000);}}
  void load();return()=>{stopped=true;controller.abort();clearTimeout(timer);};
 },[model.id,before,version]);
 async function save(enabled,config=data.config){setBusy(true);setError('');try{const r=await fetch(`/api/models/${model.id}/highlights`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,config})});const j=await r.json();if(!r.ok)throw new Error(j.error||'设置失败');setData(d=>({...d,enabled:j.enabled,config:j.config}));setDraft(null);setVersion(v=>v+1);onChange?.();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="md-section model-highlights">
  <div className="md-section-title"><h2>高光时刻</h2><label className="highlight-toggle"><input type="checkbox" checked={!!data?.enabled} disabled={!data||busy} onChange={e=>save(e.target.checked)}/>高光录制</label></div>
  <p className="highlight-explainer">人数 / TK 高光保留前 2 分钟和后 3 分钟；目标即将完成时提前保留，持续录到完成后 15 分钟。目标突然完成也会保留前置缓存。同一主播同时命中多个条件，只合并原因并延长同一份录像。</p>
  <p className="highlight-explainer">开启录制会持续接收视频。人数 / TK 首次接入或断档后预热 5 分钟，目标监控独立判断；采集间隔需不超过 10 秒。前置画面以已有缓存为限。</p>
  {data&&<div className="goal-controls"><label className="highlight-toggle"><input type="checkbox" checked={data.config.goalNotify} disabled={busy} onChange={e=>save(data.enabled,{...data.config,goalNotify:e.target.checked})}/>目标进度提醒</label><label className="highlight-toggle"><input type="checkbox" checked={data.config.goalRecord} disabled={busy} onChange={e=>save(data.enabled,{...data.config,goalRecord:e.target.checked})}/>目标高光</label><p className="highlight-explainer">剩余 ≤ {data.config.goalNearPercent}% 或进度直接跳满时提醒，每个目标每个阶段仅一次。提醒可独立开启；目标高光需同时开启上方录制开关。系统通知沿用提醒通知页的浏览器通知设置。</p>{data.goal&&<p className="highlight-explainer">{data.goal.error||Date.now()-new Date(data.goal.updated_at)>30000?'目标数据待更新':data.goal.state?.available?`${data.goal.state.goal?.description||'当前目标'} · ${data.goal.state.completed?'已完成':`剩余 ${Number(data.goal.state.remaining?.toFixed(2))}%`}`:'当前未观察到公开目标'}</p>}</div>}
  {data&&<div className="highlight-status"><span className="md-badge">{data.enabled?data.state.status:'已关闭'}</span>{data.enabled&&data.state.error&&<span role="alert">{data.state.error}</span>}<button disabled={busy} onClick={()=>setDraft(draft?null:{...data.config})}>{draft?'收起设置':'触发设置'}</button></div>}
  {draft&&<form className="highlight-settings" onSubmit={e=>{e.preventDefault();void save(data.enabled,draft);}}>
   {[['viewerRatio','人数增幅（倍，0.3 = 30%）',0.1,10,0.1],['viewerIncrease','人数至少增加',1,1000000,1],['tipMinimum','30 秒 TK 至少',1,10000000,1],['tipRatio','TK 速率倍数',1,100,0.1],['singleTip','单笔 TK 阈值',1,10000000,1],['goalNearPercent','目标剩余比例（%）',0.1,20,0.1]].map(([key,label,min,max,step])=><label key={key}>{label}<input required type="number" min={min} max={max} step={step} value={draft[key]} onChange={e=>setDraft(d=>({...d,[key]:e.target.value===''?'':Number(e.target.value)}))}/></label>)}
   <button className="primary" disabled={busy}>保存设置</button>
  </form>}
  {error&&<p className="error-banner" role="alert">{error}</p>}
  {selected&&<div className="highlight-player"><div><strong>{when(selected.triggered_at)}</strong><button onClick={()=>setSelected(null)}>关闭播放</button></div><video key={selected.id} controls autoPlay playsInline src={`/api/highlights/${selected.id}/file`} onError={()=>setError('片段暂不可播放，请检查文件是否可用。')}/></div>}
  <div className="highlight-list">{data?.items.map(h=><article key={h.id} className="highlight-item"><div><time>{when(h.triggered_at)}</time><h3>{h.reasons.map(r=>r.text).join(' · ')||'高光时刻'}</h3><p>{h.status}{h.duration_seconds>0?` · ${Math.floor(h.duration_seconds/60)} 分 ${Math.round(h.duration_seconds%60)} 秒`:''}{h.started_at?` · 片段开始 ${when(h.started_at)}`:''}</p>{h.error&&<small>{h.error}</small>}</div>{['已完成','已中断'].includes(h.status)&&Number(h.bytes)>0&&<div className="highlight-actions"><button onClick={()=>{setError('');setSelected(h);}}>播放高光</button><a href={`/api/highlights/${h.id}/file?download=1`}>下载</a></div>}</article>)}</div>
  {!data&&!error&&<div className="empty">正在读取高光…</div>}{data&&!data.items.length&&<div className="empty">尚无高光片段。开启后，系统会在监测到热度变化时自动保留。</div>}
  {data&&<div className="highlight-pagination">{before&&<button onClick={()=>{const next=[...pages];setBefore(next.pop()||null);setPages(next);setSelected(null);}}>上一页</button>}{data.nextBefore&&<button onClick={()=>{setPages(p=>[...p,before]);setBefore(data.nextBefore);setSelected(null);}}>更早高光</button>}</div>}
 </section>;
}
