import React,{useEffect,useState} from 'react';
const dur=s=>`${(s/3600).toFixed(1)} 小时`;
const level=(v,mode)=>!v?0:mode==='starts'?Math.min(4,v):v<=3600?1:v<=10800?2:v<=21600?3:4;
export default function ModelActivity({id}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[mode,setMode]=useState('seconds'),[tip,setTip]=useState('');
 useEffect(()=>{let stopped=false,timer;const abort=new AbortController();setData(null);setTip('');async function load(){try{const r=await fetch(`/api/models/${id}/activity`,{signal:abort.signal});const j=await r.json();if(!r.ok)throw Error(j.error||'活动数据读取失败');if(!stopped){setData(j);setError('');}}catch(e){if(!stopped)setError(e.message);}finally{if(!stopped)timer=setTimeout(load,60000);}}load();return()=>{stopped=true;abort.abort();clearTimeout(timer);};},[id]);
 const describe=d=>`${d.day} · ${dur(d.seconds)} · 观察到开播 ${d.starts} 次 · ${d.samples} 次采样${d.partial?` · ${d.partial} 次起点不完整`:''}`;
 const weekday=['一','二','三','四','五','六','日'];
 const leading=data?(new Date(data.daily[0].day+'T00:00:00Z').getUTCDay()+6)%7:0;
 const peak=data?.hours.reduce((best,h)=>h[mode]>best[mode]?h:best,data.hours[0]);
 return <section className="md-section md-activity"><div className="md-section-title"><h2>年度直播活动</h2><select aria-label="活动统计指标" value={mode} onChange={e=>setMode(e.target.value)}><option value="seconds">直播时长</option><option value="starts">开播次数</option></select></div>{error&&<p role="alert">{error}</p>}{data?<><div className="activity-scroll"><div className="activity-calendar" role="group" aria-label="每日直播活动">{Array.from({length:leading},(_,i)=><i key={'blank'+i}/>)}{data.daily.map(d=><button key={d.day} className={`heat-cell heat-${level(d[mode],mode)} ${!d.samples&&!d.seconds?'heat-missing':''}`} aria-label={describe(d)} title={describe(d)} onFocus={()=>setTip(describe(d))} onClick={()=>setTip(describe(d))}/>)}</div><div className="activity-range"><span>{data.daily[0].day}</span><span>{data.daily.at(-1).day}</span></div></div><div className="activity-legend"><span>{mode==='seconds'?'0 · ≤1h · ≤3h · ≤6h · >6h':'0 · 1 · 2 · 3 · ≥4 次'}</span>{[0,1,2,3,4].map(n=><i key={n} className={`heat-cell heat-${n}`}/>)}<i className="heat-cell heat-missing"/><span>无采样</span></div><p className="activity-tip" aria-live="polite">{tip||'点击日期查看记录 · UTC+8'}</p><div className="md-section-title"><h2>{mode==='seconds'?'常见活跃时段':'常见开播时段'}</h2><span>{peak?.[mode]>0?`最多：周${weekday[peak.weekday]} ${peak.hour}:00`:'等待记录'}</span></div><div className="activity-scroll"><div className="activity-hours"><span/>{Array.from({length:24},(_,h)=><span key={h}>{h}</span>)}{weekday.map((day,w)=><React.Fragment key={day}><span>周{day}</span>{data.hours.filter(h=>h.weekday===w).map(h=>{const label=`周${day} ${h.hour}:00–${h.hour+1}:00 · ${dur(h.seconds)} · 开播 ${h.starts} 次`;return <button key={h.hour} title={label} aria-label={label} className={`heat-cell heat-${h[mode]?Math.max(1,Math.ceil(h[mode]/Math.max(1,...data.hours.map(x=>x[mode]))*4)):0} ${!h.samples&&!h.seconds?'heat-missing':''}`} onClick={()=>setTip(label)} onFocus={()=>setTip(label)}/>;})}</React.Fragment>)}</div></div><details className="activity-notes"><summary>统计口径</summary>近 365 天，按 UTC+8 汇总实际采集覆盖时长。开播次数仅计连续采样中观察到的离线转在线；首次发现已在线不计开播。无采样不代表离线，颜色反映已观察到的活动。</details></>:!error&&<div className="empty">正在读取活动记录…</div>}</section>;
}
