import SessionReview from './SessionReview.jsx';
import RecentComparison from './RecentComparison.jsx';
import ProfileHistory from './ProfileHistory.jsx';
import ContentLibrary from './ContentLibrary.jsx';
import {roomLabel} from './room-state.js';
import ModelHighlights from './ModelHighlights.jsx';
import ImageViewer from './ImageViewer.jsx';
import {PublicModelProfile,usePublicInfo} from './PublicModelInfo.jsx';
import ModelActivity from './ModelActivity.jsx';
import ModelRecordings,{AutoRecordToggle} from './ModelRecordings.jsx';
import React,{useEffect,useState} from 'react';
import {ArrowLeft,Heart,Radio,Video,Monitor,ExternalLink} from 'lucide-react';
const num=n=>n==null?'—':Math.round(Number(n)).toLocaleString('zh-CN');
const duration=s=>s==null?'—':`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`;
const time=v=>v?new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
function Metric({label,value,sub}){return <div className="md-metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>;}
export default function ModelDashboard({model,history,days,setDays,Chart,onBack,onLive,onFollow,onMonitor,onRecord,onNote,recordings,onChange,refreshSeconds=5}){
 const profile=usePublicInfo(model.id,'public-profile',300000);
 const route=()=>location.hash.split('/').slice(2);
 const [deep,setDeep]=useState(route),[tab,setTab]=useState(()=>({session:'session',content:'content',changes:'changes'}[route()[0]]||'stats')),[image,setImage]=useState(null);
 useEffect(()=>{const sync=()=>{const r=route();setDeep(r);setTab({session:'session',content:'content',changes:'changes'}[r[0]]||'stats');};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[model.id]);
 const [data,setData]=useState(null),[engagement,setEngagement]=useState(null),[error,setError]=useState(''),[limit,setLimit]=useState(12),[note,setNote]=useState(model.note||'');
 useEffect(()=>{let stopped=false,timer;const abort=new AbortController();setData(null);setEngagement(null);
 async function load(){try{const results=await Promise.all(['broadcasts','engagement'].map(async name=>{const r=await fetch(`/api/models/${model.id}/${name}?days=${days}`,{signal:abort.signal});const j=await r.json();if(!r.ok)throw new Error(j.error||'数据读取失败');return j;}));if(!stopped){setData(results[0]);setEngagement(results[1]);setError('');}}catch(e){if(!stopped)setError(e.message);}finally{if(!stopped)timer=setTimeout(load,refreshSeconds*1000);}}void load();return()=>{stopped=true;abort.abort();clearTimeout(timer);};},[model.id,days,refreshSeconds]);
 useEffect(()=>{setNote(model.note||'');setLimit(12);setImage(null);},[model.id]);
 const observed=data?.daily.reduce((s,d)=>s+d.observed_seconds,0),totals=engagement?.totals;
 const hasChat=!!engagement?.coverage.length||Number(totals?.messages)>0||Number(totals?.tips)>0;
 const stateSeconds=states=>{const values=engagement?.states.filter(s=>states.includes(s.room_status));return values?.length?values.reduce((n,s)=>n+s.seconds,0):null;};
 const count=state=>engagement?.counts.find(c=>c.state===state)?.count;
 const latest=data?.sessions[0];
 return <article className="model-dashboard">
 <div className="md-nav"><button onClick={onBack}><ArrowLeft size={16}/>我的关注</button><span>主播分析</span><select aria-label="分析时间范围" value={days} onChange={e=>setDays(Number(e.target.value))}>{[7,30,90].map(n=><option value={n} key={n}>近 {n} 天</option>)}</select></div>
 <header className={`md-header ${profile.data?.background?'has-background':''}`}>{profile.data?.background&&<button className="md-background" aria-label="查看背景大图" onClick={()=>setImage({url:profile.data.background.url,alt:model.name+' 背景'})}><img src={profile.data.background.preview} alt="" style={{objectPosition:`center ${profile.data.background.position}%`}} referrerPolicy="no-referrer"/></button>}<div className="md-identity">{model.avatar_url&&<button className="md-avatar-open" aria-label="查看头像大图" onClick={()=>setImage({url:model.avatar_url,alt:model.name})}><img src={model.avatar_url} alt="" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.display='none';}}/></button>}<div><h1>{model.name}</h1><p><span className={model.fresh&&model.online?'green':''}>{!model.fresh?'待更新':roomLabel(model.room_status)}</span> · ID {model.source_id}</p></div></div><div className="md-header-controls"><AutoRecordToggle model={model} onChange={onChange}/><div className="md-actions"><button aria-pressed={!!model.favorite} onClick={onFollow}><Heart size={16}/>{model.favorite?'已关注':'关注'}</button><button aria-pressed={!!model.monitored} onClick={onMonitor}><Monitor size={16}/>{model.monitored?'已监控':'监控'}</button><button onClick={onRecord}><Video size={16}/>录制</button><button className="primary" onClick={onLive}><Radio size={16}/>看直播</button></div></div></header>
 <div className="md-tabs" role="tablist" aria-label="主播详情内容">{[['stats','统计数据'],['highlights','高光时刻'],['content','内容库'],['changes','资料变化'],['profile','官网资料'],...(deep[0]==='session'?[['session','场次回顾']]:[])].map(([value,label])=><button key={value} role="tab" id={'model-tab-'+value} aria-controls={'model-panel-'+value} aria-selected={tab===value} tabIndex={tab===value?0:-1} onClick={()=>setTab(value)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=['stats','highlights','content','changes','profile',...(deep[0]==='session'?['session']:[])];const next=e.key==='Home'?'stats':e.key==='End'?tabs.at(-1):tabs[(tabs.indexOf(tab)+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];setTab(next);document.getElementById('model-tab-'+next)?.focus();}}}>{label}</button>)}</div>
 <div role="tabpanel" id="model-panel-stats" aria-labelledby="model-tab-stats" hidden={tab!=='stats'}>
 {error&&<p role="alert" className="error-banner">{error}</p>}
 <div className="md-metrics"><Metric label="当前观看" value={model.fresh&&model.online?num(model.viewers):'—'} sub={`更新于 ${time(model.last_seen_at)}`}/><Metric label="期间采样峰值" value={num(data?.quality.peak_viewers)}/><Metric label="在线覆盖时长" value={duration(observed)}/><Metric label="公开打赏 TK" value={hasChat?num(totals?.tokens):'—'} sub={totals?.unknown_tips?`${totals.unknown_tips} 笔金额未知`:hasChat?`${num(totals?.tips)} 次打赏`:'等待互动采集'}/><Metric label="已收集弹幕" value={hasChat?num(totals?.messages):'—'}/><Metric label="活跃发言人数" value={hasChat?num(totals?.speakers):'—'} sub="按可见用户 ID 去重"/></div>
 <div className="md-charts"><section className="md-section"><div className="md-section-title"><h2>观看人数趋势</h2><span>分钟采样均值</span></div><Chart data={history} detail/></section><section className="md-section md-interaction"><div className="md-section-title"><h2>每日互动</h2><span>{engagement?.status==='connected'?'● 采集中':'未连接 / 等待公开直播'}</span></div>{engagement?.daily.length?<div className="md-bars">{engagement.daily.slice(-14).map(d=><div className="md-bar-row" key={d.day}><time>{d.day.slice(5)}</time><div><i style={{width:`${Math.max(1,d.messages/Math.max(1,...engagement.daily.map(x=>x.messages))*100)}%`}}/></div><span>{num(d.messages)} 条</span><b>{num(d.tokens)} TK</b></div>)}</div>:<div className="empty">尚无互动记录</div>}</section></div>
 <div className="md-secondary"><Metric label="最近首次观察在线" value={time(latest?.first_seen)} sub={latest?.start_known?'观察到开播':'开播时间不完整'}/><Metric label="最近结束 / 最后在线" value={time(latest?.ended_at||latest?.last_seen)} sub={latest?.end_known?'观察到下播':'下播尚未确认'}/><Metric label="私密状态区间" value={duration(stateSeconds(['private','p2p']))} sub={`${num(count('private'))} 个观察段`}/><Metric label="群组 / 计费未确认" value={duration(stateSeconds(['groupShow','paidGroupShow']))} sub={`${num(count('groupShow'))} 个观察段 · 未确认售票`}/></div>
 <div className="md-secondary"><Metric label="开票直播时长" value={duration(stateSeconds(['ticketShow']))} sub={`${num(count('ticketShow'))} 个观察段 · 房间接口明确票场`}/><Metric label="状态识别" value={model.room_details?.source==='cam'?'房间实时接口':'列表 / 历史样本'} sub="未确认与空闲不视为真实离线；旧群组记录不推断票场"/></div>
 <section className="md-section"><div className="md-section-title"><h2>直播场次</h2><span>最近 100 条 · 独立于上方时间范围</span></div><div className="md-table"><table><thead><tr><th>观察开始</th><th>结束 / 最后在线</th><th>覆盖时长</th><th>人数峰值 / 均值</th><th>弹幕 / 发言人数</th><th>公开 TK / 次数</th><th>记录</th></tr></thead><tbody>{data?.sessions.slice(0,limit).map(s=><tr key={s.id}><td>{time(s.first_seen)}</td><td>{time(s.ended_at||s.last_seen)}</td><td>{duration(s.observed_seconds)}</td><td>{num(s.peak_viewers)} / {num(s.average_viewers)}</td><td>{s.chat_observed||s.messages?num(s.messages):'—'} / {s.chat_observed||s.messages?num(s.speakers):'—'}</td><td>{s.chat_observed||s.tips?num(s.tokens):'—'} / {s.chat_observed||s.tips?num(s.tips):'—'}</td><td><span className="md-badge">{s.incomplete?'不完整':s.end_known?'已结束':'记录中'}</span><a className="block" href={`#detail/${model.id}/session/${s.id}`}>回顾本场</a></td></tr>)}</tbody></table></div>{!data?.sessions.length&&<div className="empty">暂无场次记录</div>}{data?.sessions.length>limit&&<button onClick={()=>setLimit(n=>n+12)}>显示更多</button>}</section>

 <RecentComparison id={model.id}/><ModelActivity id={model.id}/><ModelRecordings model={model} recordings={recordings} onChange={onChange}/>
 <footer className="md-footer"><span>采样 {num(data?.quality.samples)} 次 · 失败 {num(data?.quality.failures)} 次</span><details><summary>数据口径与连接记录</summary><p>仅统计观察到的公开消息和打赏，不代表总收入或到账。购买人数与售票场识别暂不可获取。匿名用户不计入去重人数，断线可能漏收；首次在线和采集缺口均标为不完整。</p>{engagement?.coverage.slice(0,8).map(c=><p key={c.id}>{time(c.started_at)} — {time(c.ended_at||c.last_seen)} · {c.reason||'连接中'}</p>)}<a href={`/api/models/${model.id}/observations`} target="_blank" rel="noreferrer">原始采样 JSON <ExternalLink size={12}/></a></details><details><summary>主播备注</summary><textarea aria-label="主播备注" maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/><button onClick={()=>onNote(note)}>保存备注</button></details></footer>
 </div><div role="tabpanel" id="model-panel-profile" aria-labelledby="model-tab-profile" hidden={tab!=='profile'}><PublicModelProfile model={model} profile={profile} onImage={setImage}/></div>
 <div role="tabpanel" id="model-panel-highlights" aria-labelledby="model-tab-highlights" hidden={tab!=='highlights'}>{tab==='highlights'&&<ModelHighlights key={model.id} model={model} onChange={onChange}/>}</div>
 <div role="tabpanel" id="model-panel-content" aria-labelledby="model-tab-content" hidden={tab!=='content'}>{tab==='content'&&<ContentLibrary key={model.id} model={model} initialKind={deep[0]==='content'?deep[1]:null} initialId={deep[0]==='content'?deep[2]:null}/>}</div>
 <div role="tabpanel" id="model-panel-changes" aria-labelledby="model-tab-changes" hidden={tab!=='changes'}>{tab==='changes'&&<ProfileHistory key={model.id} model={model}/>}</div>
 <div role="tabpanel" id="model-panel-session" aria-labelledby="model-tab-session" hidden={tab!=='session'}>{tab==='session'&&deep[1]&&<SessionReview key={deep[1]} model={model} sessionId={deep[1]}/>}</div>
 {image&&<ImageViewer key={image.url} image={image} onClose={()=>setImage(null)}/>}
 </article>;
}
