import React,{useState} from 'react';
import {useInsight,when,number,hours} from './insight-api.js';
import {ContentEditor} from './ContentLibrary.jsx';
export default function SessionReview({model,sessionId}){
 const {data,error}=useInsight(`/models/${model.id}/sessions/${sessionId}`,10000),[selected,setSelected]=useState(null),[notice,setNotice]=useState('');
 if(!data)return <section className="md-section"><p role={error?'alert':'status'}>{error||'正在读取场次回顾…'}</p></section>;
 const s=data.session,lo=Date.parse(s.first_seen),hi=Date.parse(s.ended_at||s.last_seen),span=Math.max(1,hi-lo),x=t=>Math.max(0,Math.min(900,(Date.parse(t)-lo)/span*900)),max=Math.max(1,...data.points.map(p=>p.viewers||0));
 let path='',previous=null;for(const p of data.points){if(p.viewers==null||p.gap){previous=null;continue;}const join=previous&&Date.parse(p.time)-Date.parse(previous.time)<=90000;path+=`${join?'L':'M'}${x(p.time)},${145-p.viewers/max*130} `;previous=p;}
 const peak=data.points.filter(p=>p.viewers!=null).reduce((a,p)=>!a||p.viewers>a.viewers?p:a,null);
 const markers=[...data.events.map(e=>({at:e.created_at,label:e.title,detail:e.detail})),...data.goals.filter(g=>!data.events.some(e=>String(e.payload.goalSignalId)===String(g.id))).map(g=>({at:g.observed_at,label:g.kind==='goalComplete'?'目标完成':'目标接近完成',detail:g.payload.text})),...data.tips.map(t=>({at:t.time,label:`${number(t.tokens)} TK · ${t.tips} 次公开打赏`,detail:'分钟聚合，金额未知的打赏不计入 TK'})),...(peak?[{at:peak.time,label:`本场分钟均值峰值 ${number(peak.viewers)} 人`,detail:'点击定位附近录像'}]:[])].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));
 function seek(at){const time=Date.parse(at),m=data.media.find(m=>['已完成','已中断'].includes(m.status)&&Number(m.bytes)>0&&time>=Date.parse(m.started_at)&&time<Date.parse(m.started_at)+m.duration_seconds*1000);if(!m){setNotice('这个时间点没有可播放的已归档录像。');return;}setNotice('已按录像开始时间定位，实际画面可能有数秒偏差。');setSelected({item:m,seek:Math.max(0,(time-Date.parse(m.started_at))/1000)});}
 return <div className="session-review"><section className="md-section"><div className="md-section-title"><h2>场次回顾 #{s.id}</h2><a href={`#detail/${model.id}`}>返回统计</a></div>{error&&<p role="alert">{error}</p>}<p>{when(s.first_seen)} — {when(s.ended_at||s.last_seen)} · 覆盖 {hours(s.observed_seconds)} · {s.incomplete?'记录不完整':s.end_known?'已结束':'持续观察中'}</p><p className="muted">曲线为分钟观看均值，断档不连线；金色点为公开打赏，竖线为目标或高光事件，底部短线为有效采集覆盖。点击曲线或事件定位录像，未录到的时间不会跳到其他片段。</p>
 <div className="insight-filters"><span>采样峰值 <strong>{number(s.peak_viewers)} 人</strong></span><span>采样均值 <strong>{number(s.viewer_samples?s.viewer_sum/s.viewer_samples:null)} 人</strong></span><span>公开打赏 <strong>{number(data.tips.reduce((n,t)=>n+(t.tokens||0),0))} TK</strong></span></div><div className="session-chart"><svg viewBox="0 0 900 190" role="img" aria-label="场次人数、打赏与采集覆盖时间轴"><path d={path} fill="none" stroke="#ff4264" strokeWidth="2.5"/>{data.coverage.map((c,i)=><line key={i} x1={x(c.started_at)} x2={x(c.ended_at)} y1="179" y2="179" stroke="#3c9879" strokeWidth="5"/>)}{data.events.filter(e=>['highlight','goalComplete','goalNear'].includes(e.kind)).map(e=><g key={e.id} role="button" tabIndex="0" aria-label={e.title+'，定位录像'} onClick={()=>seek(e.created_at)} onKeyDown={event=>event.key==='Enter'&&seek(e.created_at)}><title>{when(e.created_at)} {e.title}</title><line x1={x(e.created_at)} x2={x(e.created_at)} y1="10" y2="170" stroke="#8a91a0" strokeDasharray="3 4"/><rect x={x(e.created_at)-5} y="10" width="10" height="160" fill="transparent"/></g>)}{data.tips.map((t,i)=><circle key={i} cx={x(t.time)} cy="161" r="4" fill="#e7b661"><title>{number(t.tokens)} TK</title></circle>)}{data.points.filter(p=>p.viewers!=null).map((p,i)=><circle key={i} role="button" tabIndex="0" aria-label={`${when(p.time)} ${number(p.viewers)} 人，定位录像`} cx={x(p.time)} cy={145-p.viewers/max*130} r="5" fill="#ff4264" onClick={()=>seek(p.time)} onKeyDown={e=>e.key==='Enter'&&seek(p.time)}/>)}</svg></div><div className="md-section-title"><span>{when(s.first_seen)}</span><span>{when(s.ended_at||s.last_seen)}</span></div><p role="status">{notice}</p></section>
 {selected&&<ContentEditor key={selected.item.kind+selected.item.id} item={selected.item} seek={selected.seek} onClose={()=>setSelected(null)}/>}
 <section className="md-section"><h2>本场录像与高光</h2><div className="insight-feed">{data.media.map(m=><article key={m.kind+m.id}><div><h3>{m.title||m.filename}</h3><p>{when(m.started_at)} · {m.kind==='highlight'?'高光':'录像'} · {m.status}</p></div><button onClick={()=>setSelected({item:m,seek:0})}>查看与整理</button></article>)}</div>{!data.media.length&&<p className="empty">本场未关联到录像</p>}</section>
 <section className="md-section"><h2>事件时间线</h2><div className="insight-feed">{markers.map((m,i)=><article key={i}><div><time>{when(m.at)}</time><h3>{m.label}</h3><p>{m.detail}</p></div><button onClick={()=>seek(m.at)}>定位录像</button></article>)}</div>{!markers.length&&<p className="empty">本场尚无关键事件</p>}</section></div>;
}
